import { LuShoppingBag, LuShoppingBasket, LuStore } from "react-icons/lu"
import { SiCarrefour, SiLidl } from "react-icons/si"

export const getEmojiForIcon = (iconId: string) => {
  const mapping: Record<string, string> = {
    milk: '🥛',
    leche: '🥛',
    cheese: '🧀',
    queso: '🧀',
    butter: '🧈',
    mantequilla: '🧈',
    yogurt: '🍦',
    yogur: '🍦',
    bread: '🍞',
    pan: '🍞',
    bakery: '🥐',
    panaderia: '🥐',
    bolleria: '🥐',
    apple: '🍎',
    manzana: '🍎',
    banana: '🍌',
    platano: '🍌',
    orange: '🍊',
    naranja: '🍊',
    grapes: '🍇',
    uvas: '🍇',
    strawberry: '🍓',
    fresa: '🍓',
    tomato: '🍅',
    tomate: '🍅',
    potato: '🥔',
    patata: '🥔',
    papas: '🥔',
    carrot: '🥕',
    zanahoria: '🥕',
    lettuce: '🥬',
    lechuga: '🥬',
    onion: '🧅',
    cebolla: '🧅',
    chicken: '🍗',
    pollo: '🍗',
    beef: '🥩',
    carne: '🥩',
    pork: '🥓',
    cerdo: '🥓',
    fish: '🐟',
    pescado: '🐟',
    water: '💧',
    agua: '💧',
    juice: '🧃',
    jugo: '🧃',
    zumo: '🧃',
    soda: '🥤',
    refresco: '🥤',
    coca: '🥤',
    coffee: '☕',
    cafe: '☕',
    tea: '🍵',
    te: '🍵',
    rice: '🍚',
    arroz: '🍚',
    pasta: '🍝',
    flour: '🌾',
    harina: '🌾',
    sugar: '🍭',
    azucar: '🍭',
    salt: '🧂',
    aceite: '🧴',
    chips: '🍟',
    cookie: '🍪',
    galletas: '🍪',
    chocolate: '🍫',
    candy: '🍬',
    dulces: '🍬',
    caramelos: '🍬',
    generic: '🛒'
  };

  return mapping[iconId] || '🛒';
};

export const CART_LOGOS = [
  { id: 'default', label: 'Default', icon: LuShoppingBag, color: 'text-blue-600' },
  { id: 'carrefour', label: 'Carrefour', icon: LuStore, color: 'text-blue-500' },
  { id: 'mercadona', label: 'Mercadona', icon: LuShoppingBasket, color: 'text-green-600' },
  { id: 'lidl', label: 'Lidl', icon: LuStore, color: 'text-blue-700' },
  { id: 'alcampo', label: 'Alcampo', icon: LuShoppingBasket, color: 'text-red-600' }
]
